version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"

  - package-ecosystem: "pip"
    directory: "/.github/workflows/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "build"