# Project information
site_name: 'api-generator'
site_description: 'A library for generating programs that interface with the official Guild Wars 2 API.'
site_author: 'GW2ToolBelt'
site_url: 'https://gw2toolbelt.github.io/api-generator'

# Copyright
copyright: Copyright &copy; 2019 - 2023 Leon Linhart


edit_uri: 'tree/master/docs'
remote_branch: 'gh-pages'

docs_dir: 'build/mkdocs/sources'

# Repository
repo_name: 'api-generator'
repo_url: 'https://github.com/GW2ToolBelt/api-generator'


# Configuration
theme:
  name: 'material'
  icon:
    logo: material/hammer-wrench
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/GW2ToolBelt'


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details



# Navigation
nav:
  - 'api-generator':
    - 'Overview': index.md
    - 'Changelog': changelog.md
    - 'Contributing': contributing.md
    - 'License': license.md

  - 'Guild Wars 2 API':
    - 'General': gw2api/general.md
    - 'API Version 1': gw2api/v1.md
    - 'API Version 2': gw2api/v2.md
    - 'API Issues': gw2api/issues.md

  - 'User Guide':
    - 'Getting Started': userguide/introduction.md
#    - 'Schema': userguide/schema.md

  - 'Developer Guide':
    - 'Getting Started': devguide/introduction.md
#    - 'DSL': devguide/dsl.md

  - 'API Reference': api/index.html