/*
 * Copyright (c) 2019-2022 Leon Linhart
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.gw2tb.apigen

public enum class APIv2Endpoint(internal val endpointName: String) {
    V2_ACCOUNT("/Account"),
    V2_ACCOUNT_ACHIEVEMENTS("/Account/Achievements"),
    V2_ACCOUNT_BANK("/Account/Bank"),
    V2_ACCOUNT_BUILDSTORAGE("/Account/BuildStorage"),
    V2_ACCOUNT_DAILYCRAFTING("/Account/DailyCrafting"),
    V2_ACCOUNT_DUNGEONS("/Account/Dungeons"),
    V2_ACCOUNT_DYES("/Account/Dyes"),
    V2_ACCOUNT_EMOTES("/Account/Emotes"),
    V2_ACCOUNT_FINISHERS("/Account/Finishers"),
    V2_ACCOUNT_GLIDERS("/Account/Gliders"),
    V2_ACCOUNT_HOME("/Account/Home"),
    V2_ACCOUNT_HOME_CATS("/Account/Home/Cats"),
    V2_ACCOUNT_HOME_NODES("/Account/Home/Nodes"),
    V2_ACCOUNT_INVENTORY("/Account/Inventory"),
    V2_ACCOUNT_LEGENDARYARMORY("/Account/LegendaryArmory"),
    V2_ACCOUNT_LUCK("/Account/Luck"),
    V2_ACCOUNT_MAILCARRIERS("/Account/Mailcarriers"),
    V2_ACCOUNT_MAPCHESTS("/Account/MapChests"),
    V2_ACCOUNT_MASTERIES("/Account/Masteries"),
    V2_ACCOUNT_MASTERY_POINTS("/Account/Mastery/Points"),
    V2_ACCOUNT_MATERIALS("/Account/Materials"),
    V2_ACCOUNT_MINIS("/Account/Minis"),
    V2_ACCOUNT_MOUNTS("/Account/Mounts"),
    V2_ACCOUNT_MOUNTS_SKIN("/Account/Mounts/Skins"),
    V2_ACCOUNT_MOUNTS_TYPES("/Account/Mounts/Types"),
    V2_ACCOUNT_NOVELTIES("/Account/Novelties"),
    V2_ACCOUNT_OUTFITS("/Account/Outfits"),
    V2_ACCOUNT_PVP_HEROES("/Account/PvP/Heroes"),
    V2_ACCOUNT_RAIDS("/Account/Raids"),
    V2_ACCOUNT_RECIPES("/Account/Recipes"),
    V2_ACCOUNT_SKINS("/Account/Skins"),
    V2_ACCOUNT_TITLES("/Account/Titles"),
    V2_ACCOUNT_WALLET("/Account/Wallet"),
    V2_ACCOUNT_WORLDBOSSES("/Account/WorldBosses"),
    V2_ACHIEVEMENTS("/Achievements"),
    V2_ACHIEVEMENTS_CATEGORIES("/Achievements/Categories"),
    V2_ACHIEVEMENTS_DAILY("/Achievements/Daily"),
    V2_ACHIEVEMENTS_DAILY_TOMORROW("/Achievements/Daily/Tomorrow"),
    V2_ACHIEVEMENTS_GROUPS("/Achievements/Groups"),
    V2_BACKSTORY("/Backstory"),
    V2_BACKSTORY_ANSWERS("/Backstory/Answers"),
    V2_BACKSTORY_QUESTIONS("/Backstory/Questions"),
    V2_BUILD("/Build"),
    V2_CHARACTERS("/Characters"),
    V2_CHARACTERS_BACKSTORY("/Characters/:ID/Backstory"),
    V2_CHARACTERS_BUILDTABS("/Characters/:ID/BuildTabs"),
    V2_CHARACTERS_BUILDTABS_ACTIVE("/Characters/:ID/BuildTabs/Active"),
    V2_CHARACTERS_CORE("/Characters/:ID/Core"),
    V2_CHARACTERS_CRAFTING("/Characters/:ID/Crafting"),
    V2_CHARACTERS_EQUIPMENT("/Characters/:ID/Equipment"),
    V2_CHARACTERS_EQUIPMENTTABS("/Characters/:ID/EquipmentTabs"),
    V2_CHARACTERS_EQUIPMENTTABS_ACTIVE("/Characters/:ID/EquipmentTabs/Active"),
    V2_CHARACTERS_HEROPOINTS("/Characters/:ID/HeroPoints"),
    V2_CHARACTERS_INVENTORY("/Characters/:ID/Inventory"),
    V2_CHARACTERS_QUESTS("/Characters/:ID/Quests"),
    V2_CHARACTERS_RECIPES("/Characters/:ID/Recipes"),
    V2_CHARACTERS_SAB("/Characters/:ID/SAB"),
    V2_CHARACTERS_SKILLS("/Characters/:ID/Skills"),
    V2_CHARACTERS_SPECIALIZATIONS("/Characters/:ID/Specializations"),
    V2_CHARACTERS_TRAINING("/Characters/:ID/Training"),
    V2_COLORS("/Colors"),
    V2_COMMERCE_DELIVERY("/Commerce/Delivery"),
    V2_COMMERCE_EXCHANGE("/Commerce/Exchange"),
    V2_COMMERCE_LISTINGS("/Commerce/Listings"),
    V2_COMMERCE_PRICES("/Commerce/Prices"),
    V2_COMMERCE_TRANSACTIONS("/Commerce/Transactions"),
    V2_CONTINENTS("/Continents"),
    V2_CONTINENTS_FLOORS("/Continents/:ID/Floors"),
    V2_CREATESUBTOKEN("/CreateSubToken"),
    V2_CURRENCIES("/Currencies"),
    V2_DAILYCRAFTING("/DailyCrafting"),
    V2_DUNGEONS("/Dungeons"),
    V2_EMBLEM("/Emblem"),
    V2_EMOTES("/Emotes"),
    V2_FILES("/Files"),
    V2_FINISHERS("/Finishers"),
    V2_GLIDERS("/Gliders"),
    V2_GUILD("/Guild/:ID"),
    V2_GUILD_LOG("/Guild/:ID/Log"),
    V2_GUILD_MEMBERS("/Guild/:ID/Members"),
    V2_GUILD_RANKS("/Guild/:ID/Ranks"),
    V2_GUILD_STASH("/Guild/:ID/Stash"),
    V2_GUILD_STORAGE("/Guild/:ID/Storage"),
    V2_GUILD_TEAMS("/Guild/:ID/Teams"),
    V2_GUILD_TREASURY("/Guild/:ID/Treasury"),
    V2_GUILD_UPGRADES("/Guild/:ID/Upgrades"),
    V2_GUILD_SEARCH("/Guild/Search"),
    V2_GUILD_PERMISSIONS("/Guild/Permissions"),
    V2_GUILD_UPGRADES__STATIC("/Guild/Upgrades"),
    V2_HOME("/Home"),
    V2_HOME_CATS("/Home/Cats"),
    V2_HOME_NODES("/Home/Nodes"),
    V2_ITEMS("/Items"),
    V2_ITEMSTATS("/ItemStats"),
    V2_LEGENDARYARMORY("/LegendaryArmory"),
    V2_LEGENDS("/Legends"),
    V2_MAILCARRIERS("/Mailcarriers"),
    V2_MAPCHESTS("/MapChests"),
    V2_MAPS("/Maps"),
    V2_MASTERIES("/Masteries"),
    V2_MATERIALS("/Materials"),
    V2_MINIS("/Minis"),
    V2_MOUNTS("/Mounts"),
    V2_MOUNTS_SKINS("/Mounts/Skins"),
    V2_MOUNTS_TYPES("/Mounts/Types"),
    V2_NOVELTIES("/Novelties"),
    V2_OUTFITS("/Outfits"),
    V2_PETS("/Pets"),
    V2_PROFESSIONS("/Professions"),
    V2_PVP("/PvP"),
    V2_PVP_AMULETS("/PvP/Amulets"),
    V2_PVP_GAMES("/PvP/Games"),
    V2_PVP_HEROES("/PvP/Heroes"),
    V2_PVP_RANKS("/PvP/Ranks"),
    V2_PVP_SEASONS("/PvP/Seasons"),
    V2_PVP_SEASONS_LEADERBOARDS("/PvP/Seasons/:ID/Leaderboards"),
    V2_PVP_STANDINGS("/PvP/Standings"),
    V2_PVP_STATS("/PvP/Stats"),
    V2_QUAGGANS("/Quaggans"),
    V2_QUESTS("/Quests"),
    V2_RACES("/Races"),
    V2_RAIDS("/Raids"),
    V2_RECIPES("/Recipes"),
    V2_RECIPES_SEARCH("/Recipes/Search"),
    V2_SKILLS("/Skills"),
    V2_SKINS("/Skins"),
    V2_SPECIALIZATIONS("/Specializations"),
    V2_STORIES("/Stories"),
    V2_STORIES_SEASONS("/Stories/Seasons"),
    V2_TITLES("/Titles"),
    V2_TOKENINFO("/TokenInfo"),
    V2_TRAITS("/Traits"),
    V2_WORLDBOSSES("/WorldBosses"),
    V2_WORLDS("/Worlds"),
    V2_WVW_ABILITIES("/WvW/Abilities"),
    V2_WVW_MATCHES("/WvW/Matches"),
    V2_WVW_MATCHES_OVERVIEW("/WvW/Matches/Overview"),
    V2_WVW_MATCHES_SCORES("/WvW/Matches/Scores"),
    V2_WVW_MATCHES_STATS("/WvW/Matches/Stats"),
    V2_WVW_OBJECTIVES("/WvW/Objectives"),
    V2_WVW_RANKS("/WvW/Ranks"),
    V2_WVW_UPGRADES("/WvW/Upgrades")
}