name: Publish docs
on: workflow_dispatch


jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install --no-deps -r .github/workflows/mkdocs-requirements.txt

      - name: Build documentation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: mkdocs --info -S --show-version
          gradle-home-cache-cleanup: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/mkdocs/site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1