name: Publish docs
on: workflow_dispatch

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material

      - name: Gradle MkDocs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: mkdocs --info -S --show-version
          gradle-home-cache-cleanup: true

      - name: Deploy
        uses: GW2ToolBelt/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/mkdocs/site